# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true
    
    csrf_protection:
        enabled: true
    
   # For CSRF tokens and routing to work through reverse proxies (like Railway & Ngrok):
    trusted_proxies: '127.0.0.1,REMOTE_ADDR,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16'
    
    # Tell Symfony to trust ALL standard proxy headers forwarded by Nginx/Railway
    trusted_headers: ['x-forwarded-for', 'x-forwarded-host', 'x-forwarded-proto', 'x-forwarded-port']

    # Combine all allowed domains into ONE clean, fallback regular expression string
    trusted_hosts: ['^(localhost|127\.0\.0\.1|10\.0\.2\.2|.*\.ngrok-free\.dev|.*\.ngrok\.io|.*\.railway\.app)$']



when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file